name: Build
on: [pull_request, workflow_dispatch]
jobs:
  cocoapods:
    name: CocoaPods (Xcode 13)
    runs-on: macOS-11
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use Xcode 13
        run: sudo xcode-select -switch /Applications/Xcode_13.1.app
      - name: Install CocoaPod dependencies
        run: pod install
      - name: Run pod lib lint 
        run: pod lib lint
  carthage:
    name: Carthage (Xcode 13)
    runs-on: macOS-11
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use Xcode 13
        run: sudo xcode-select -switch /Applications/Xcode_13.1.app
      - name: Run carthage build
        run: carthage build --no-skip-current
